### ISSUE TITLE
[!] Invalid Choice

### ISSUE THREAD

**Issue by bucky67gto** [Viralmaniar/SMWYG-Show-Me-What-You-Got#1]
Looks helpful, but after install on rolling kali get [!] Invalid Choice no matter the number selected.

**Comment by Museon23** [comment]
same ^

**Comment by audiofox** [comment]
2 ways to get around that:
    1) use  $ python3 SMWYG.py 
    2) or if you prefer to use python you can use quotes around your options "1." , "2.", "3."

Hope this helps.

**Comment by Museon23** [comment]
Thank you @audiofox  - all good.
