### ISSUE TITLE
gotcha.pw is down

### ISSUE THREAD

**Issue by thehappydinoa** [Viralmaniar/SMWYG-Show-Me-What-You-Got#3]
Hey, `https://gotcha.pw` is down or broken. I am not sure if you have another service in mind or have any insight into the site.

**Comment by clouedoc** [comment]
For reference, someone archived a page of it [here](http://archive.li/vuoRX#selection-145.5-145.17).

**Comment by cyclo-techtwister** [comment]
Is this site of use for this project (have yet to try this "SMWYG-Show-Me-What-You-Got
"tool)?
https://haveibeenpwned.com/

**Comment by clouedoc** [comment]
gotcha.pw is up again !

**Comment by cyclo-techtwister** [comment]
@jesuiscamille 
> 
> 
> gotcha.pw is up again !

Not on my end:   404 Not Found

**Comment by theoneandonly-vector** [comment]
anybody with a backup-site so we can copy and host ourselfs?
